services:
  backend:
    image: esg-platform-backend:latest   # Same image for all instances
    container_name: ${INSTANCE_ID}-backend
    ports:
      - "${API_PORT}:5003"
    environment:
      - INSTANCE_ID=${INSTANCE_ID}
      - DOMAIN=${DOMAIN}
    volumes:
      - ./instance_data/${INSTANCE_ID}/db:/app/src/database
      - ./instance_data/${INSTANCE_ID}/dist:/app/src/static
    restart: always
