version: '3.8'

services:
  backend:
    container_name: ${INSTANCE_ID}-backend
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "${API_PORT}:5003"
    environment:
      - INSTANCE_ID=${INSTANCE_ID}
      - DOMAIN=${DOMAIN}
    volumes:
      - ./instance_data/${INSTANCE_ID}/db:/app/src/database
    restart: always
